pub mod auth;
pub mod users;
pub mod content;
pub mod extensions;
pub mod intergations;
pub mod schedule;
pub mod list;
pub mod proxy;
pub mod config;
pub mod progress;
pub mod backups;
pub mod logs;
#[cfg(feature = "discord-rpc")]
pub mod discord;